"""autoware_carla_scenario – CARLA scenario testing framework.

Public API re-exported for convenience::

    from autoware_carla_scenario import (
        AutowareEgoEntity,
        AutowareEntity,
        CarlaDriverEntity,
        DriverClientConfig,
        EGO_ROLE_NAME,
        EntityRole,
        ScenarioRunner,
        CarlaScenarioFixture,
        CarlaServerManager,
        AndCondition,
        BaseCondition,
        BaseScenario,
        CarlaWorldPose,
        CollisionCondition,
        ComparisonRule,
        ElapsedTimeCondition,
        EntityLanePositionCondition,
        NotCondition,
        OrCondition,
        SpeedCondition,
        DistanceCoordinateSystem,
        SpeedCoordinateSystem,
        SpeedDirection,
        StandstillCondition,
        StickyCondition,
        EgoConfig,
        EgoVehicle,
        Lanelet2Pose,
        MapManager,
        OpenDrivePose,
        ScenarioQueue,
        ScenarioResult,
        TimeoutCondition,
        to_carla_location,
        to_carla_world,
        to_lanelet2,
        to_map_frame,
        to_opendrive,
        find_nearest_traffic_light,
        frame_of,
        lanelet2_traffic_light_id_to_opendrive_controller_id,
        find_actor_by_role_name,
        TrafficLightTarget,
        RoutingAction,
        TrafficSignalAction,
        # Entity
        SpawnLocation,
        SpawnPointIndex,
        SpawnTransform,
        VehicleEntity,
        VehicleEntityConfig,
        # Kinematics
        CoordinateFrame,
        FrameMismatchError,
        Vector3,
        AbsoluteVelocity,
        RelativeVelocity,
        FrenetVelocity,
        AbsoluteAcceleration,
        RelativeAcceleration,
        FrenetAcceleration,
    )

Imports are deferred (PEP 562) so that lightweight subpackages such as
``autoware_carla_scenario.ui`` can be imported without pulling in heavy
native dependencies (CARLA, lanelet2).
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .actions import (
        BaseAction as BaseAction,
        EnvironmentAction as EnvironmentAction,
        LaneChangeAction as LaneChangeAction,
        LaneChangeDirection as LaneChangeDirection,
        TickTiming as TickTiming,
        TrafficLightTarget as TrafficLightTarget,
        RoutingAction as RoutingAction,
        SetSpeedAction as SetSpeedAction,
        TrafficSignalAction as TrafficSignalAction,
        TurnAction as TurnAction,
        TurnDirection as TurnDirection,
        WalkStraightAction as WalkStraightAction,
    )
    from .camera_recorder import CameraRecorder as CameraRecorder
    from .conditions import (
        AccelerationCondition as AccelerationCondition,
        AccelerationDirection as AccelerationDirection,
        AlwaysTrueCondition as AlwaysTrueCondition,
        AndCondition as AndCondition,
        BaseCondition as BaseCondition,
        CollisionCondition as CollisionCondition,
        CollisionTargetType as CollisionTargetType,
        ComparisonRule as ComparisonRule,
        ElapsedTimeCondition as ElapsedTimeCondition,
        EntityDistanceCondition as EntityDistanceCondition,
        RelativeDistanceType as RelativeDistanceType,
        EntityExistenceCondition as EntityExistenceCondition,
        EntityLanePositionCondition as EntityLanePositionCondition,
        EntityPositionDistanceCondition as EntityPositionDistanceCondition,
        NotCondition as NotCondition,
        OrCondition as OrCondition,
        PersistentCondition as PersistentCondition,
        RelativeSpeedCondition as RelativeSpeedCondition,
        ScalarComparisonRule as ScalarComparisonRule,
        ScenarioResult as ScenarioResult,
        SpeedCondition as SpeedCondition,
        DistanceCoordinateSystem as DistanceCoordinateSystem,
        SpeedCoordinateSystem as SpeedCoordinateSystem,
        SpeedDirection as SpeedDirection,
        StandstillCondition as StandstillCondition,
        StickyCondition as StickyCondition,
        TemporaryStopCondition as TemporaryStopCondition,
        TimeHeadwayCondition as TimeHeadwayCondition,
        TimeToCollisionCondition as TimeToCollisionCondition,
        TimeoutCondition as TimeoutCondition,
        TrafficSignalCondition as TrafficSignalCondition,
        WaypointCheckType as WaypointCheckType,
        WaypointCondition as WaypointCondition,
        find_actor_by_role_name as find_actor_by_role_name,
    )
    from .constants import EGO_ROLE_NAME as EGO_ROLE_NAME
    from .coordinate import (
        CarlaWorldPose as CarlaWorldPose,
        CoordinateFrame as CoordinateFrame,
        FrameMismatchError as FrameMismatchError,
        GroundProjectionConfig as GroundProjectionConfig,
        Lanelet2Pose as Lanelet2Pose,
        MapManager as MapManager,
        OpenDrivePose as OpenDrivePose,
        find_nearest_traffic_light as find_nearest_traffic_light,
        frame_of as frame_of,
        get_stop_line_linestrings as get_stop_line_linestrings,
        get_stop_line_poses as get_stop_line_poses,
        get_stop_line_poses_with_following as get_stop_line_poses_with_following,
        lanelet2_traffic_light_id_to_opendrive_controller_id as lanelet2_traffic_light_id_to_opendrive_controller_id,
        snap_to_carla_road as snap_to_carla_road,
        to_carla_location as to_carla_location,
        to_carla_world as to_carla_world,
        to_lanelet2 as to_lanelet2,
        to_map_frame as to_map_frame,
        to_opendrive as to_opendrive,
    )
    from .driver import (
        BaseEgoDriverClient as BaseEgoDriverClient,
        ControlConfig as ControlConfig,
        DriverCameraConfig as DriverCameraConfig,
        DriverClientConfig as DriverClientConfig,
        EgoDriverGrpcClient as EgoDriverGrpcClient,
    )
    from .autoware_bridge import (
        AutowareBridge as AutowareBridge,
        AutowareBridgeConfig as AutowareBridgeConfig,
        BridgePose as BridgePose,
        FakeAutowareBridge as FakeAutowareBridge,
        GrpcAutowareBridgeServer as GrpcAutowareBridgeServer,
    )
    from .entity import (
        AutowareEgoEntity as AutowareEgoEntity,
        AutowareEntity as AutowareEntity,
        CarlaDriverEntity as CarlaDriverEntity,
        EgoVehicle as EgoVehicle,
        PedestrianEntity as PedestrianEntity,
        PedestrianEntityConfig as PedestrianEntityConfig,
        SpawnLocation as SpawnLocation,
        SpawnPointIndex as SpawnPointIndex,
        SpawnTransform as SpawnTransform,
        VehicleEntity as VehicleEntity,
        VehicleEntityConfig as VehicleEntityConfig,
    )
    from .entity_role import EntityRole as EntityRole
    from .kinematics import (
        AbsoluteAcceleration as AbsoluteAcceleration,
        AbsoluteVelocity as AbsoluteVelocity,
        FrenetAcceleration as FrenetAcceleration,
        FrenetVelocity as FrenetVelocity,
        RelativeAcceleration as RelativeAcceleration,
        RelativeVelocity as RelativeVelocity,
        Vector3 as Vector3,
    )
    from .pytest_fixtures import CarlaScenarioFixture as CarlaScenarioFixture
    from .registry import (
        BuildScenarioFn as BuildScenarioFn,
        ScenarioBuilder as ScenarioBuilder,
        get_conf_dirs as get_conf_dirs,
        get_scenario_builder as get_scenario_builder,
        get_scenario_registry as get_scenario_registry,
        load_scenario_plugins as load_scenario_plugins,
        register_conf_dir as register_conf_dir,
        register_scenario as register_scenario,
        register_scenario_builder as register_scenario_builder,
        unregister_conf_dir as unregister_conf_dir,
        unregister_scenario as unregister_scenario,
    )
    from .scenario_base import (
        BaseScenario as BaseScenario,
        EgoConfig as EgoConfig,
    )
    from .scenario_config import (
        DriverCameraSpec as DriverCameraSpec,
        DriverConfig as DriverConfig,
        DriverControlSpec as DriverControlSpec,
        EgoVehicleConfig as EgoVehicleConfig,
        EntityConfig as EntityConfig,
        MapConfig as MapConfig,
        NpcVehicleConfig as NpcVehicleConfig,
        ServerConfig as ServerConfig,
        SweepConfig as SweepConfig,
    )
    from .scenario_queue import ScenarioQueue as ScenarioQueue
    from .scenario_runner import ScenarioRunner as ScenarioRunner
    from .sensor import (
        CameraSensorBase as CameraSensorBase,
        CameraSensorConfig as CameraSensorConfig,
        CarlaCameraSensor as CarlaCameraSensor,
        CarlaCameraSensorConfig as CarlaCameraSensorConfig,
    )
    from .server import CarlaServerManager as CarlaServerManager
    from .traffic import (
        NullTrafficBackend as NullTrafficBackend,
        TrafficBackend as TrafficBackend,
        TrafficBackendError as TrafficBackendError,
        TrafficBackendUnavailable as TrafficBackendUnavailable,
        TrafficConfig as TrafficConfig,
        TrafficContext as TrafficContext,
        TrafficManagerBackend as TrafficManagerBackend,
        TrafficManagerBackendConfig as TrafficManagerBackendConfig,
        register_backend as register_backend,
    )


__all__ = [
    "EGO_ROLE_NAME",
    "EntityRole",
    "ScenarioRunner",
    "CarlaScenarioFixture",
    "CarlaServerManager",
    # Scenario package extension API
    "register_scenario",
    "register_scenario_builder",
    "unregister_scenario",
    "get_scenario_registry",
    "get_scenario_builder",
    "register_conf_dir",
    "unregister_conf_dir",
    "get_conf_dirs",
    "load_scenario_plugins",
    "ScenarioBuilder",
    "BuildScenarioFn",
    # Shared scenario config dataclasses
    "ServerConfig",
    "MapConfig",
    "EntityConfig",
    "EgoVehicleConfig",
    "NpcVehicleConfig",
    "SweepConfig",
    # Traffic backends
    "NullTrafficBackend",
    "TrafficBackend",
    "TrafficBackendError",
    "TrafficBackendUnavailable",
    "TrafficConfig",
    "TrafficContext",
    "TrafficManagerBackend",
    "TrafficManagerBackendConfig",
    "register_backend",
    "AccelerationCondition",
    "AccelerationDirection",
    "EntityDistanceCondition",
    "RelativeDistanceType",
    "EntityExistenceCondition",
    "RelativeSpeedCondition",
    "AlwaysTrueCondition",
    "AndCondition",
    "BaseCondition",
    "BaseScenario",
    "CarlaWorldPose",
    "CollisionCondition",
    "CollisionTargetType",
    "ComparisonRule",
    "ElapsedTimeCondition",
    "EntityLanePositionCondition",
    "EntityPositionDistanceCondition",
    "NotCondition",
    "OrCondition",
    "PersistentCondition",
    "ScalarComparisonRule",
    "SpeedCondition",
    "DistanceCoordinateSystem",
    "SpeedCoordinateSystem",
    "SpeedDirection",
    "StandstillCondition",
    "StickyCondition",
    "TemporaryStopCondition",
    "TimeHeadwayCondition",
    "TimeToCollisionCondition",
    "AutowareEgoEntity",
    "AutowareEntity",
    # autoware bridge
    "AutowareBridge",
    "AutowareBridgeConfig",
    "BridgePose",
    "FakeAutowareBridge",
    "GrpcAutowareBridgeServer",
    "BaseEgoDriverClient",
    "CarlaDriverEntity",
    "ControlConfig",
    "DriverCameraConfig",
    "DriverCameraSpec",
    "DriverClientConfig",
    "DriverConfig",
    "DriverControlSpec",
    "EgoDriverGrpcClient",
    "EgoConfig",
    "EgoVehicle",
    "PedestrianEntity",
    "PedestrianEntityConfig",
    "SpawnLocation",
    "SpawnPointIndex",
    "SpawnTransform",
    "VehicleEntity",
    "VehicleEntityConfig",
    "Lanelet2Pose",
    "MapManager",
    "OpenDrivePose",
    "ScenarioQueue",
    "ScenarioResult",
    "TimeoutCondition",
    "to_carla_location",
    "to_carla_world",
    "to_lanelet2",
    "to_map_frame",
    "to_opendrive",
    "find_nearest_traffic_light",
    "frame_of",
    "get_stop_line_linestrings",
    "get_stop_line_poses",
    "get_stop_line_poses_with_following",
    "GroundProjectionConfig",
    "snap_to_carla_road",
    "lanelet2_traffic_light_id_to_opendrive_controller_id",
    "find_actor_by_role_name",
    # Kinematics
    "CoordinateFrame",
    "FrameMismatchError",
    "Vector3",
    "AbsoluteVelocity",
    "RelativeVelocity",
    "FrenetVelocity",
    "AbsoluteAcceleration",
    "RelativeAcceleration",
    "FrenetAcceleration",
    # Actions
    "BaseAction",
    "EnvironmentAction",
    "LaneChangeAction",
    "LaneChangeDirection",
    "TickTiming",
    "TrafficLightTarget",
    "RoutingAction",
    "SetSpeedAction",
    "TrafficSignalAction",
    "TrafficSignalCondition",
    "WaypointCheckType",
    "WaypointCondition",
    "TurnAction",
    "TurnDirection",
    "WalkStraightAction",
    # Sensors
    "CameraRecorder",
    "CameraSensorBase",
    "CameraSensorConfig",
    "CarlaCameraSensor",
    "CarlaCameraSensorConfig",
]

# ---------------------------------------------------------------------------
# Lazy import mapping: name -> (module_path, attribute_name)
# ---------------------------------------------------------------------------

_LAZY_IMPORTS: dict[str, tuple[str, str]] = {
    # actions
    "BaseAction": (".actions", "BaseAction"),
    "EnvironmentAction": (".actions", "EnvironmentAction"),
    "LaneChangeAction": (".actions", "LaneChangeAction"),
    "LaneChangeDirection": (".actions", "LaneChangeDirection"),
    "TickTiming": (".actions", "TickTiming"),
    "TrafficLightTarget": (".actions", "TrafficLightTarget"),
    "RoutingAction": (".actions", "RoutingAction"),
    "SetSpeedAction": (".actions", "SetSpeedAction"),
    "TrafficSignalAction": (".actions", "TrafficSignalAction"),
    "TurnAction": (".actions", "TurnAction"),
    "WalkStraightAction": (".actions", "WalkStraightAction"),
    "TurnDirection": (".actions", "TurnDirection"),
    # camera / sensor
    "CameraRecorder": (".camera_recorder", "CameraRecorder"),
    "CameraSensorBase": (".sensor", "CameraSensorBase"),
    "CameraSensorConfig": (".sensor", "CameraSensorConfig"),
    "CarlaCameraSensor": (".sensor", "CarlaCameraSensor"),
    "CarlaCameraSensorConfig": (".sensor", "CarlaCameraSensorConfig"),
    # scenario runner / queue / server
    "ScenarioRunner": (".scenario_runner", "ScenarioRunner"),
    "ScenarioQueue": (".scenario_queue", "ScenarioQueue"),
    "CarlaServerManager": (".server", "CarlaServerManager"),
    # conditions
    "AccelerationCondition": (".conditions", "AccelerationCondition"),
    "AccelerationDirection": (".conditions", "AccelerationDirection"),
    "RelativeSpeedCondition": (".conditions", "RelativeSpeedCondition"),
    "EntityDistanceCondition": (".conditions", "EntityDistanceCondition"),
    "RelativeDistanceType": (".conditions", "RelativeDistanceType"),
    "EntityExistenceCondition": (".conditions", "EntityExistenceCondition"),
    "AlwaysTrueCondition": (".conditions", "AlwaysTrueCondition"),
    "AndCondition": (".conditions", "AndCondition"),
    "BaseCondition": (".conditions", "BaseCondition"),
    "CollisionCondition": (".conditions", "CollisionCondition"),
    "CollisionTargetType": (".conditions", "CollisionTargetType"),
    "ComparisonRule": (".conditions", "ComparisonRule"),
    "ElapsedTimeCondition": (".conditions", "ElapsedTimeCondition"),
    "EntityLanePositionCondition": (".conditions", "EntityLanePositionCondition"),
    "EntityPositionDistanceCondition": (
        ".conditions",
        "EntityPositionDistanceCondition",
    ),
    "NotCondition": (".conditions", "NotCondition"),
    "OrCondition": (".conditions", "OrCondition"),
    "PersistentCondition": (".conditions", "PersistentCondition"),
    "ScalarComparisonRule": (".conditions", "ScalarComparisonRule"),
    "ScenarioResult": (".conditions", "ScenarioResult"),
    "SpeedCondition": (".conditions", "SpeedCondition"),
    "DistanceCoordinateSystem": (".conditions", "DistanceCoordinateSystem"),
    "SpeedCoordinateSystem": (".conditions", "SpeedCoordinateSystem"),
    "SpeedDirection": (".conditions", "SpeedDirection"),
    "StandstillCondition": (".conditions", "StandstillCondition"),
    "StickyCondition": (".conditions", "StickyCondition"),
    "TemporaryStopCondition": (".conditions", "TemporaryStopCondition"),
    "TimeHeadwayCondition": (".conditions", "TimeHeadwayCondition"),
    "TimeToCollisionCondition": (".conditions", "TimeToCollisionCondition"),
    "TimeoutCondition": (".conditions", "TimeoutCondition"),
    "TrafficSignalCondition": (".conditions", "TrafficSignalCondition"),
    "WaypointCheckType": (".conditions", "WaypointCheckType"),
    "WaypointCondition": (".conditions", "WaypointCondition"),
    "find_actor_by_role_name": (".conditions", "find_actor_by_role_name"),
    # constants / entity_role
    "EGO_ROLE_NAME": (".constants", "EGO_ROLE_NAME"),
    "EntityRole": (".entity_role", "EntityRole"),
    # coordinate
    "CarlaWorldPose": (".coordinate", "CarlaWorldPose"),
    "CoordinateFrame": (".coordinate", "CoordinateFrame"),
    "FrameMismatchError": (".coordinate", "FrameMismatchError"),
    "GroundProjectionConfig": (".coordinate", "GroundProjectionConfig"),
    "Lanelet2Pose": (".coordinate", "Lanelet2Pose"),
    "MapManager": (".coordinate", "MapManager"),
    "OpenDrivePose": (".coordinate", "OpenDrivePose"),
    "frame_of": (".coordinate", "frame_of"),
    "get_stop_line_poses": (".coordinate", "get_stop_line_poses"),
    "get_stop_line_poses_with_following": (
        ".coordinate",
        "get_stop_line_poses_with_following",
    ),
    "snap_to_carla_road": (".coordinate", "snap_to_carla_road"),
    "to_carla_location": (".coordinate", "to_carla_location"),
    "to_carla_world": (".coordinate", "to_carla_world"),
    "to_lanelet2": (".coordinate", "to_lanelet2"),
    "to_map_frame": (".coordinate", "to_map_frame"),
    "to_opendrive": (".coordinate", "to_opendrive"),
    # entity
    "AutowareEgoEntity": (".entity", "AutowareEgoEntity"),
    "AutowareEntity": (".entity", "AutowareEntity"),
    "CarlaDriverEntity": (".entity", "CarlaDriverEntity"),
    "EgoVehicle": (".entity", "EgoVehicle"),
    "PedestrianEntity": (".entity", "PedestrianEntity"),
    "PedestrianEntityConfig": (".entity", "PedestrianEntityConfig"),
    "SpawnLocation": (".entity", "SpawnLocation"),
    "SpawnPointIndex": (".entity", "SpawnPointIndex"),
    "SpawnTransform": (".entity", "SpawnTransform"),
    "VehicleEntity": (".entity", "VehicleEntity"),
    "VehicleEntityConfig": (".entity", "VehicleEntityConfig"),
    # kinematics
    "AbsoluteAcceleration": (".kinematics", "AbsoluteAcceleration"),
    "AbsoluteVelocity": (".kinematics", "AbsoluteVelocity"),
    "FrenetAcceleration": (".kinematics", "FrenetAcceleration"),
    "FrenetVelocity": (".kinematics", "FrenetVelocity"),
    "RelativeAcceleration": (".kinematics", "RelativeAcceleration"),
    "RelativeVelocity": (".kinematics", "RelativeVelocity"),
    "Vector3": (".kinematics", "Vector3"),
    # pytest
    "CarlaScenarioFixture": (".pytest_fixtures", "CarlaScenarioFixture"),
    # scenario base
    "BaseScenario": (".scenario_base", "BaseScenario"),
    "EgoConfig": (".scenario_base", "EgoConfig"),
    # scenario package extension API (registry)
    "register_scenario": (".registry", "register_scenario"),
    "register_scenario_builder": (".registry", "register_scenario_builder"),
    "unregister_scenario": (".registry", "unregister_scenario"),
    "get_scenario_registry": (".registry", "get_scenario_registry"),
    "get_scenario_builder": (".registry", "get_scenario_builder"),
    "register_conf_dir": (".registry", "register_conf_dir"),
    "unregister_conf_dir": (".registry", "unregister_conf_dir"),
    "get_conf_dirs": (".registry", "get_conf_dirs"),
    "load_scenario_plugins": (".registry", "load_scenario_plugins"),
    "ScenarioBuilder": (".registry", "ScenarioBuilder"),
    "BuildScenarioFn": (".registry", "BuildScenarioFn"),
    # shared scenario config dataclasses
    "ServerConfig": (".scenario_config", "ServerConfig"),
    "MapConfig": (".scenario_config", "MapConfig"),
    "EntityConfig": (".scenario_config", "EntityConfig"),
    "EgoVehicleConfig": (".scenario_config", "EgoVehicleConfig"),
    "NpcVehicleConfig": (".scenario_config", "NpcVehicleConfig"),
    "SweepConfig": (".scenario_config", "SweepConfig"),
    "DriverConfig": (".scenario_config", "DriverConfig"),
    "DriverCameraSpec": (".scenario_config", "DriverCameraSpec"),
    "DriverControlSpec": (".scenario_config", "DriverControlSpec"),
    # traffic backends
    "NullTrafficBackend": (".traffic", "NullTrafficBackend"),
    "TrafficBackend": (".traffic", "TrafficBackend"),
    "TrafficBackendError": (".traffic", "TrafficBackendError"),
    "TrafficBackendUnavailable": (".traffic", "TrafficBackendUnavailable"),
    "TrafficConfig": (".traffic", "TrafficConfig"),
    "TrafficContext": (".traffic", "TrafficContext"),
    "TrafficManagerBackend": (".traffic.traffic_manager", "TrafficManagerBackend"),
    "TrafficManagerBackendConfig": (".traffic", "TrafficManagerBackendConfig"),
    "register_backend": (".traffic", "register_backend"),
    # autoware bridge
    "AutowareBridge": (".autoware_bridge", "AutowareBridge"),
    "AutowareBridgeConfig": (".autoware_bridge", "AutowareBridgeConfig"),
    "BridgePose": (".autoware_bridge", "BridgePose"),
    "FakeAutowareBridge": (".autoware_bridge", "FakeAutowareBridge"),
    "GrpcAutowareBridgeServer": (".autoware_bridge", "GrpcAutowareBridgeServer"),
    # driver
    "BaseEgoDriverClient": (".driver", "BaseEgoDriverClient"),
    "ControlConfig": (".driver", "ControlConfig"),
    "DriverCameraConfig": (".driver", "DriverCameraConfig"),
    "DriverClientConfig": (".driver", "DriverClientConfig"),
    "EgoDriverGrpcClient": (".driver", "EgoDriverGrpcClient"),
    # utils
    "find_nearest_traffic_light": (".coordinate", "find_nearest_traffic_light"),
    "get_stop_line_linestrings": (".coordinate", "get_stop_line_linestrings"),
    "lanelet2_traffic_light_id_to_opendrive_controller_id": (
        ".coordinate",
        "lanelet2_traffic_light_id_to_opendrive_controller_id",
    ),
}


def __getattr__(name: str) -> object:
    """Lazily import public symbols on first access (PEP 562)."""
    if name in _LAZY_IMPORTS:
        module_path, attr = _LAZY_IMPORTS[name]
        import importlib  # noqa: PLC0415

        mod = importlib.import_module(module_path, __name__)
        value = getattr(mod, attr)
        # Cache on the module so subsequent lookups are fast.
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
